spring.application.name=backend

# Configuration of the SGBD SQLite (original DB name preserved)
spring.datasource.url=jdbc:sqlite:db/sports_together.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=


# Configuration of Hibernate (original property key preserved)
spring.jpa.databaseplatform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Server port
server.port=8080